<div class="main small_content">
	<p class="selection_message wide">Deploy up to 2 cloud servers for free!</p>
	<div class="selections">
		<ul>
		<?php foreach($this->selections as $class => $data): ?>
			<li>
				<a class="selection_item<?php echo $data['disabled'] ? ' disabled' : '' ?>"
					href="<?php echo '/' . ($data['disabled'] ? 'apology' : $this->next . '/' . $class) ?>">
					<span class="selection_image <?php echo $this->type . ' ' . $class ?>">.</span>
					<span class="control selection_button <?php echo $data['type'] ?>"><?php echo $data['text'] ?></span>
					</a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>

	<div class="clearfix"></div>

	<div id="info_space">
		<img src="/css/images/logo_big.png" />
		<h4>What is Tenbrain?</h4>
		With Tenbrain,  you can automate the cost of running your infrastructure across multiple clouds providers.  Tenbrain fully manages scaling, monitoring, logging and all aspects of your cloud infrastructure. With Tenbrain, you’ll never have to bang your head trying to figure out the cost of running your infrastructure in the cloud. It’s as simple as entering your IT budget, type of infrastructure and providers you wish to use. And with flexible payment options for any size company, you can- Save your Brain, While saving Money!
	</div>

</div>