<div class="main small_content">
	<p class="selection_message wide">Deploy up to 2 cloud servers for free!</p>
	<div class="selections">
		<ul>
		<?php foreach($this->selections as $class => $data): ?>
			<li>
				<a class="selection_item<?php echo $data['disabled'] ? ' disabled' : '' ?>"
					href="<?php echo '/' . ($data['disabled'] ? 'apology' : $this->next . '/' . $class) ?>">
					<span class="selection_image <?php echo $this->type . ' ' . $class ?>">.</span>
					<span class="control selection_button <?php echo $data['type'] ?>"><?php echo $data['text'] ?></span>
					</a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>

	<div class="clearfix"></div>

	<div id="info_space">
		<img src="/css/images/sample.jpg" />
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
	</div>

</div>