<div class="main big_content">
	<span class="info_image info">Info</span>
	<h2 class="info_message">Privacy Policy</h2>

	<p class="content">
		We respect your privacy. We will not release your private information or information that can identify you as an individual to any partner or 3rd party.
		Any information you provide on the Tenbrain site will be held with the utmost care and will not be used in ways that you have not consented to. A more detailed explanation about how we safeguard your personal information is described below. If you have any questions, please do not hesitate to let us know.
		The Cloud Providers credentials entered into the Tenbrain are used exclusively per your instructions through the Tenbrain interface. These credentials are stored in encrypted form in the database and are not released to 3rd parties, or transmitted across any network in unencrypted form.
	</p>
	
	<h4 class="logo_start">Sensible data protection and encryption</h4>
	<p class="content">
		All Cloud Provider credentials, public and private keys, passwords are stored in encrypted format, using strong cryptographic algorithms.
		Tenbrain will never use your passwords, authentication data, private or public keys, data stored on your S3 buckets.
	</p>
	
	<h4 class="logo_start">Access to computing instances</h4>
	<p class="content">
		You authorize Tenbrain support staff to log in over SSH protocol to your computing instances and perform configuration and maintenance tasks. This can be done when a) you ask for support, b) when suspicious activity detected on your instance, that may damage or interrupt Tenbrain system operations, data or instances of other Tenbrain clients.
		If you do not wish to authorize access to your computing instances, you must <a href="mailto:admin@Tenbrain.com">send a notice to us</a> 
	</p>
	
	<h4 class="logo_start">Use of Cookies</h4>
	<p class="content">
		enbrain uses HTTP cookies to simplify user login and account management. These cookies will not be sold, rented, loaned, eaten, or otherwise disclosed.
	</p>
	
	<div class="clearfix"></div>
</div>