<div class="main big_content">
	<span class="info_image info">Info</span>
	<h2 class="info_message">Cancellation and Refund Policy</h2>

	<h4 class="logo_start">Cancellation</h4>
	<p class="content">
		You can cancel your monthly subscription simply by cancelling your PayPal subscription in the PayPal control panel.
		Once cancelled, your account will remain active until the next due date.
		Past the due date, if no payment has been received, your account will be deactivated. You will no longer be able to log in to the Tenbrain control panel and your instances, farms, and applications will no longer be controlled by Tenbrain. However, no instances are terminated upon service cancellation, so they will continue to run, unless you terminate them.
	</p>
	
	<h4 class="logo_start">Refunds</h4>
	<p class="content">
		No refunds can be made, neither for full nor for partial month periods.
	</p>
	
	<div class="clearfix"></div>
</div>