<div class="main big_content">
	<span class="info_image info">Info</span>
	<h2 class="info_message">Terms Of Service</h2>

	<h4 class="logo_start">1. Your Agreement with Tenbrain</h4>
	<p class="content">
		<b>1.1.</b> Your use of the Tenbrain (the “Service”) is governed by this agreement (the “Terms”). “Tenbrain” means Tenbrain, Inc., and its subsidiaries or affiliates involved in providing the Service.<br />
		<b>1.2.</b> In order to use the Service, you must first agree to the Terms. You understand and agree that Tenbrain will treat your use of the Service as acceptance of the Terms from that point onwards.<br />
		<b>1.3.</b> You may not use the Service if you are a person barred from receiving the Service under the laws of the United States or other countries including the country in which you are resident or from which you use the Service. You affirm that you are over the age of 13, as the Service is not intended for children under 13.
	</p>
	
	<h4 class="logo_start">2. Your Account and Use of the Service</h4>
	<p class="content">
		<b>2.1.</b> You must provide accurate and complete registration information any time you register to use the Service. You are responsible for the security of your passwords and for any use of your account. If you become aware of any unauthorized use of your password or of your account, you agree to notify Tenbrain immediately.<br />
		<b>2.2.</b> You may neither share nor re-sell your Tenbrain account to 3rd parties.<br />
		<b>2.3.</b> Your use of the Service must comply with all applicable laws, regulations and ordinances, including any laws regarding the export of data or softwar<br />
		<b>2.4.</b> You agree not to engage in any activity that interferes with or disrupts the Service (or the servers and networks which are connected to the Service).<br />
		<b>2.5.</b> You may not circumvent the domain name restriction of the Tenbrain Development edition, and must use a domain of the form yourcompany.development.Tenbrain.net.<br />
	</p>
	
	<h4 class="logo_start">3. Service Policies and Privacy</h4>
	<p class="content">
		The Service shall be subject to the privacy policy for the Service available at <a href="/legal/privacy">http://beta.tenbrain.com/legal/privacy</a>. You agree to the use of your data in accordance with “Tenbrain” privacy policies.
	</p>

	<h4 class="logo_start">4. Payment and Cancellation of service</h4>
	<p class="content">
		<b>4.1.</b> The Service is billed in advance on a one time and monthly basis and is non-refundable. There will be no refunds or credits for partial months of service, or refunds for months unused with an open account. In order to treat everyone equally, no exceptions will be made.<br />
		<b>4.2.</b> Amazon, Rackspace and GoGrid will charge you for the usage of their web services per your agreement with them, when you registered for an AWS, Rackspace or GoGrid account.<br />
		<b>4.3.</b> You are solely responsible for properly canceling your Tenbrain subscription. An email request to cancel your subscription is not considered cancellation. You can cancel your account at any time by simply cancelling PayPal subscription in PayPal control panel.<br />
		<b>4.4.</b> If you cancel the Service before the end of your current paid up month, your account will remain active until the next due date. After the due date, if no payment received, your account will be disabled. You will no longer be able to log in to Tenbrain control panel and your instances will not be controlled by Tenbrain. Tenbrain will not terminate your instances upon service cancellation.<br />
	</p>
	
	<h4 class="logo_start">5. Proprietary Rights</h4>
	<p class="content">
		<b>5.1.</b> You acknowledge and agree that Tenbrain (or Tenbrain's licensors) own all legal right, title and interest in and to the Service, including any intellectual property rights which subsist in the Service (whether those rights happen to be registered or not, and wherever in the world those rights may exist).<br />
		<b>5.2.</b> Unless you have agreed otherwise in writing with Tenbrain, nothing in the Terms gives you a right to use any of Tenbrain's trade names, trade marks, service marks, logos, domain names, and other distinctive brand features.<br />
		<b>5.3.</b> Except as provided in Section 7, Tenbrain acknowledges and agrees that it obtains no right, title or interest from you (or your licensors) under these Terms in or to any Content or the Application that you create, submit, post, transmit or display on, or through, the Service, including any intellectual property rights which subsist in that Content and the Application (whether those rights happen to be registered or not, and wherever in the world those rights may exist). Unless you have agreed otherwise in writing with Tenbrain, you agree that you are responsible for protecting and enforcing those rights and that Tenbrain has no obligation to do so on your behalf.<br />
	</p>
	
	<h4 class="logo_start">6. License from Tenbrain and Restrictions</h4>
	<p class="content">
		<b>6.1.</b> Tenbrain gives you a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use the software provided to you by Tenbrain as part of the Service as provided to you by Tenbrain. This license is for the sole purpose of enabling you to use and enjoy the benefit of the Service as provided by Tenbrain, in the manner permitted by the Terms.<br />
		<b>6.2.</b> Tenbrain uses Amazon Web Services, Rackspace and GoGrid. You agree to uphold License Agreement to whatever extent it applies to your usage of the Cloud Providers and Tenbrain.<br />
	</p>
	
	<h4 class="logo_start">7. License from You</h4>
	<p class="content">
		<b>7.1.</b> Tenbrain claims no ownership or control over any Content or Application. You retain copyright and any other rights you already hold in the Content and/or Application, and you are responsible for protecting those rights, as appropriate. By submitting, posting or displaying the Content on or through the Service you give Tenbrain a worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute such Content for the sole purpose of enabling Tenbrain to provide you with the Service in accordance with its privacy policy. Furthermore, by creating an Application through use of the Service, you give Tenbrain a worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute such Application for the sole purpose of enabling Tenbrain to provide you with the Service in accordance with its privacy policy.<br />
		<b>7.2.</b> You agree that Tenbrain, in its sole discretion, may use your trade names, trademarks, service marks, logos, domain names and other distinctive brand features in presentations, marketing materials, customer lists, financial reports and Web site listings (including links to your website) for the purpose of advertising or publicizing your use of the Service.<br />
	</p>
	
	<h4 class="logo_start">8. Software Updates</h4>
	<p class="content">
		The Software which you use may be upgraded with new features and tools from time to time by Tenbrain. These updates are designed to improve, enhance and further develop the Service and may take the form of bug fixes, enhanced functions, new software modules and completely new versions. You agree to receive such updates (and permit Tenbrain to deliver these to you) as part of your use of the Service.
	</p>
	
	<h4 class="logo_start">9. Modification and Termination of the Service</h4>
	<p class="content">
		<b>9.1.</b> Tenbrain is constantly innovating in order to provide the best possible experience for its users. You acknowledge and agree that the form and nature of the Service which Tenbrain provides may change from time to time without prior notice to you.<br />
		<b>9.2.</b> You may discontinue your use of the Service at any time. Tenbrain may, at any time, terminate your use of the Service if (A) you have breached any provision of the Terms (or have acted in manner which clearly shows that you do not intend to, or are unable to comply with the provisions of the Terms) or (B) Tenbrain is required to do so by law (for example, where the provision of the Service to you is, or becomes, unlawful). Further, Tenbrain may terminate your use of the Service for any reason with ninety (30) days prior written notice.<br />
		<b>9.3.</b> Upon any termination of the Service, these Terms will also terminate, but Section 14.7 shall continue to be effective after these Terms are terminated.<br />
	</p>
	
	<h4 class="logo_start">10. EXCLUSION OF WARRANTIES</h4>
	<p class="content">
		<b>10.1.</b> NOTHING IN THESE TERMS, INCLUDING SECTIONS 10 AND 12, SHALL EXCLUDE OR LIMIT Tenbrain's WARRANTY OR LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW.<br />
		<b>10.2.</b> YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK AND THAT THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE”.<br />
		<b>10.3.</b> Tenbrain, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS MAKE NO EXPRESS WARRANTIES AND DISCLAIM ALL IMPLIED WARRANTIES REGARDING THE SERVICE INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, Tenbrain, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: (A) YOUR USE OF THE SERVICE WILL MEET YOUR REQUIREMENTS, (B) YOUR USE OF THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, AND (C) USAGE DATA PROVIDED THROUGH THE SERVICE WILL BE ACCURATE.<br />
	</p>
	
	<h4 class="logo_start">11. LIMITATION OF LIABILITY</h4>
	<p class="content">
		<b>11.1.</b> SUBJECT TO SECTION 10.1 ABOVE, YOU EXPRESSLY UNDERSTAND AND AGREE THAT Tenbrain, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL CONSEQUENTIAL OR EXEMPLARY DAMAGES WHICH MAY BE INCURRED BY YOU, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY. THIS SHALL INCLUDE, BUT NOT BE LIMITED TO, ANY LOSS OF PROFIT (WHETHERF INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL OR BUSINESS REPUTATION, ANY LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS.<br />
		<b>11.2.</b> THE LIMITATIONS ON Tenbrain'S LIABILITY TO YOU IN PARAGRAPH 10.1 ABOVE SHALL APPLY WHETHER OR NOT Tenbrain HAS BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.<br />
	</p>
	
	<h4 class="logo_start">12. Indemnification</h4>
	<p class="content">
		You agree to hold harmless and indemnify Tenbrain, and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners, (collectively “Tenbrain and Partners”) from and against any third party claim arising from or in any way related to (a) your breach of the Terms, (b) your use of the Service, (c) your violation of applicable laws, rules or regulations in connection with the Service, or (d) your Content or your Application, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorney's fees, of every kind and nature. In such a case, Tenbrain will provide you with written notice of such claim, suit or action.
	</p>
	
	<h4 class="logo_start">13. Changes to the Terms</h4>
	<p class="content">
		<b>13.1.</b> Tenbrain may make changes to the Terms from time to time. When these changes are made, Tenbrain will make a new copy of the Terms available at <a href="/">http://tenbrain.com/legal/terms</a><br />
		<b>13.2.</b> You understand and agree that if you use the Service after the date on which the Terms have changed, Tenbrain will treat your use as acceptance of the updated Terms.<br />
	</p>
	
	<h4 class="logo_start">14. General Legal Terms</h4>
	<p class="content">
		<b>14.1.</b> The Terms constitute the whole legal agreement between you and Tenbrain and govern your use of the Service (but excluding any services which Tenbrain may provide to you under a separate written agreement), and completely replace any prior agreements between you and Tenbrain in relation to the Service.<br />
		<b>14.2.</b> There are no third party beneficiaries to these Terms. The parties are independent contractors, and nothing in these Terms creates an agency, partnership or joint venture.<br />
		<b>14.3.</b> If Tenbrain provides you with a translation of the English language version of these Terms, the English language version of these Terms will control if there is any conflict.<br />
		<b>14.4.</b> You agree that Tenbrain may provide you with notices, including those regarding changes to the Terms, by email, regular mail, or postings on the Service.<br />
		<b>14.5.</b> You agree that if Tenbrain does not exercise or enforce any legal right or remedy which is contained in the Terms (or which Tenbrain has the benefit of under any applicable law), this will not be taken to be a formal waiver of Tenbrain's rights and that those rights or remedies will still be available to Tenbrain.<br />
		<b>14.6.</b> Tenbrain shall not be liable for failing or delaying performance of its obligations resulting from any condition beyond its reasonable control, including but not limited to, governmental action, acts of terrorism, earthquake, fire, flood or other acts of God, labor conditions, power failures, and Internet disturbances.<br />
		<b>14.7.</b> The Terms, and your relationship with Tenbrain under the Terms, shall be governed by the laws of the State of Georgia without regard to its conflict of laws provisions. You and Tenbrain agree to submit to the exclusive jurisdiction of the courts located within the county of Fulton, Georgia to resolve any legal matter arising from the Terms. Notwithstanding this, you agree that Tenbrain shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction.<br />
	</p>
	
	<div class="clearfix"></div>
</div>