<div class="main small_content">
	<p class="selection_message wide">Enter your credit card information</p>

		<form action="" method="post" accept-charset="utf-8" >
		<div class="payment container">

			<div class="payment amount-field"><?php echo $this->form->cc_amount;?><div class="field-descr">incl. $0.30 fixed and 2.9% fees</div></div>
			<div class="payment amount-field"><?php echo $this->form->number;?></div>
			<div class="payment amount-field"><?php echo $this->form->type;?></div>
			<div class="payment amount-field"><?php echo $this->form->month;?><?php echo $this->form->year;?></div>
			<div class="payment amount-field"><?php echo $this->form->cvv2;?></div>

			<?php echo $this->form->submit; ?>
			<?php echo $this->form->payment_type;?>
		</div>
		</form>
</div>