<div class="main big_content">
	<div class="reg_form">
		<h2>Sign Up</h2>
		<form action="" method="post" accept-charset="utf-8" class="account_form signin">			
			<h3>TenBrain Account</h3>

				<p class="input_wrapper">
					<label for="username">Username</label>				
					<?php echo $this->form->username; ?>
				</p>
				
				<p class="input_wrapper">
					<label for="username">Email</label>				
					<?php echo $this->form->email; ?>
				</p>
				
				<p class="input_wrapper">
					<?php echo $this->form->submit; ?>			
				</p>
		</form>	
	</div>

	<div class="clearfix"></div>
</div>
