<div class="main big_content">
	<div class="reg_form">
		<h2>Sign Up</h2>
		<h3>Create your TenBrain Account</h3>
		<form action="" method="post" accept-charset="utf-8" class="account_form signup">
			<p class="input_wrapper">
				<label for="username">Username</label>:
				<?php echo $this->form->username; ?>
			</p>

			<p class="input_wrapper">
				<label for="password">Password</label>:	
				<?php echo $this->form->password; ?>
			</p>

			<p class="input_wrapper">
				<label for="email">Email</label>:
				<?php echo $this->form->email; ?>
			</p>
			
			<div class="input_wrapper">
				<?php echo $this->form->ReCaptcha; ?>
			</div>

			<p class="input_wrapper">
				<?php echo $this->form->submit; ?>	
			</p>
		</form>
		<p class="input_wrapper center">
			Already have an account? 
			<a href="/auth/login" class="blue underlined_dash">Sign in now</a>
		</p>
	</div>
	
	<h3>Sign up with your account from:</h3>
	<ul class="third_parties">
		<li class="control third_party big facebook">
			<a href="/auth/facebookconnect" title="Sign Up with Facebook" class="social">Facebook</a>		
		</li>
	
		<li class="control third_party big twitter">
			<a href="/auth/twitterconnect" title="Sign Up with Twitter" class="social">Twitter</a>		
		</li>
	
		<li class="control third_party big google">
			<a href="/auth/openidconnect" title="Sign Up with Google" class="social">Google</a>		
		</li>
	</ul>
	<div class="clearfix"></div>
</div>