<div class="main big_content">
	<div class="reg_form">
		<h2>Sign In</h2>
		<form action="" method="post" accept-charset="utf-8" class="account_form signin">			
			<h3>Sign in with your TenBrain <br/> Account</h3>

				<p class="input_wrapper">
					<label for="username">Username/Email</label>				
					<?php echo $this->form->username; ?>
				</p>
				
				<p class="input_wrapper">
					<label for="password">Password</label>				
					<?php echo $this->form->password; ?>
				</p>

				<p class="input_wrapper center account_error"></p>
				
				<p class="input_wrapper">
					<?php echo $this->form->remember; ?>				
					<label for="remember">Remember me</label>
					<?php echo $this->form->submit; ?>			
				</p>
				
				<p class="input_wrapper center">
					<a href="/auth/forgot" class="blue underlined_dash">Forgot your password?</a>			
				</p>
				
				<p class="input_wrapper center">
					Don't have an account? <a href="/auth/register" class="blue underlined_dash">Sign up now</a>			
				</p>

		</form>	
	</div>

	<h3>Sign in with your account from:</h3>

	<ul class="third_parties">
		<li class="control third_party big facebook">
			<a href="/auth/facebookconnect" title="Sign In with Facebook" class="social">Facebook</a>		
		</li>
		<li class="control third_party big twitter">
			<a href="/auth/twitterconnect" title="Sign In with Twitter" class="social">Twitter</a>		
		</li>
		<li class="control third_party big google">
			<a href="/auth/googleconnect" title="Sign In with Google" class="social">Google</a>
		</li>
	</ul>

	<div class="clearfix"></div>
</div>
