<div class="main big_content">
	<div class="reg_form">

		<h2>Forgot your password?</h2>

		<form action="" method="post" accept-charset="utf-8">		<p>We will send reset password instructions to the email address associated with your account.</p>

			<p class="input_wrapper center">
				<label for="forgot_password_username_email">Email</label>:
				<?php echo $this->form->email; ?>	
			</p>
	
			<div class="input_wrapper">	
				<?php echo $this->form->ReCaptcha; ?>
			</div>
	
			<p class="input_wrapper center">
				<?php echo $this->form->submit; ?>		
			</p>

		</form>	
	</div>
</div>