<div class="main big_content">
	<div class="reg_form">
		<form action="" method="post" accept-charset="utf-8" class="account_form signin">			
			<h3>Sign in with your TenBrain <br> Account</h3>

				<p class="text_input_wrapper">
					<label for="login">Username/Email</label>				
					<?php echo $this->form->login; ?>
				</p>
				
				<p class="text_input_wrapper">
					<label for="password">Password</label>				
					<?php echo $this->form->password; ?>
				</p>

				<p class="input_wrapper center account_error"></p>
				
				<div class="sign_in_settings">
					<div class="remember_forgot">
						<?php echo $this->form->remember; ?>				
						<label for="remember">Remember me</label>
						<a href="/account/forgot_password" class="blue underlined_dash forgot">Forgot your password?</a>
						</div>
					<div class="sign_in_button">
						<?php echo $this->form->submit; ?>			
					</div>
					
					<div class="no_account">
						<div class="no_account_text">Don't have an account?</div>
						<a href="/account/sign_up" class="blue underlined_dash">Sign up now</a>			
					</div>
				</div>
				
				

		</form>	
	</div>

	<h3>Sign in with your account from:</h3>

	<div id="third_party_big">
		<ul class="third_parties">
			<li class="control third_party big facebook">
				<a href="/account/facebook_connect" title="Sign In with Facebook" class="social">Facebook</a>		
			</li>
			<li class="control third_party big twitter">
				<a href="/account/twitter_connect" title="Sign In with Twitter" class="social">Twitter</a>		
			</li>
			<li class="control third_party big google">
				<a href="/account/google_connect" title="Sign In with Google" class="social">Google</a>
			</li>
		</ul>
	</div>

	<div class="clearfix"></div>
</div>
