<div class="main big_content">
	<div class="reg_form">
		<h3>Create your TenBrain <br/ > Account</h3>
		<form action="" method="post" accept-charset="utf-8" class="account_form signup">
			<p class="text_input_wrapper">
				<label for="username">Username</label>
				<?php echo $this->form->username; ?>
			</p>

			<p class="text_input_wrapper">
				<label for="password">Password</label>
				<?php echo $this->form->password; ?>
			</p>

			<p class="text_input_wrapper">
				<label for="email">Email</label>
				<?php echo $this->form->email; ?>
			</p>
			
			<div class="input_wrapper">
				<?php echo $this->form->ReCaptcha; ?>
			</div>

			<div class="input_wrapper">
				<?php echo $this->form->submit; ?>	
			</div>
		</form>
		<div class="have_account">
			<div class="have_account_text">Already have an account?</div>
			<a href="/account/sign_in" class="blue underlined_dash">Sign in now</a>
		</div>
	</div>
	
	<h3>Sign up with your account from:</h3>
	
	<div id="third_party_big">
		<ul class="third_parties">
			<li class="control third_party big facebook">
				<a href="/account/facebook_connect" title="Sign Up with Facebook" class="social">Facebook</a>		
			</li>
		
			<li class="control third_party big twitter">
				<a href="/account/twitter_connect" title="Sign Up with Twitter" class="social">Twitter</a>		
			</li>
		
			<li class="control third_party big google">
				<a href="/account/google_connect" title="Sign Up with Google" class="social">Google</a>		
			</li>
		</ul>
	</div>
	
	<div class="clearfix"></div>
</div>