<div class="main big_content">
	<span class="info_image info">Info</span>
	<h2 class="info_message">Tenbrain Features - Coming Soon!</h2>

	<h4 class="logo_start">We take the complexity out of Cloud budgeting.</h4>
	<p class="content">
		Tenbrain is a Open Source Cloud cost controller Platform (CccP). We manage the cost of provisioning servers in the cloud and enterprise. With Tenbrain, you get more than just a management platform. You get CccP - Our Cloud Cost Controller Platform - Get rid of the budgeting nightmare of the Cloud, and Save money, While Saving your Brain.
	</p>

	<h4 class="logo_start">CccP - Cloud cost control Platform</h4>
	<p class="content">
		Do you know what it will cost you each month to deploy to the Cloud? One of the most frustrating and complex parts about the cloud is not how you get stuff running, it’s trying to figure out how much that will cost once you do get it running. With Tenbrain’s CccP, you no longer need to worry about that. You simply input what your expected monthly budget and Tenbrain takes care of the rest. Tenbrain’s CccP will automatically select the most competitive Cloud provider to deploy your infrastructure on. Or it will deploy across multiple cloud providers, automatically integrating your applications stacks- CccP does for Cloud IT budgeting what the Cloud did for the data center.
	</p>
	
	<h4 class="logo_start">TenStacks- Fully integrated Open Source Components.</h4>
	<p class="content">
		Deploying Open Source applications can be time consuming. There are options available to deploy open source applications encapsulated in a instance. But this still leaves you with a critical component missing when it comes to enterprise deployments and integration. With Tenstacks, you deploy complete infrastructure stacks that are 100% integrated and 100% Open Source!
	</p>
	
	<h4 class="logo_start">TenAMP- Automation, Monitoring and Provisioning</h4>
	<p class="content">
		Automated provisioning and management of both your private and public cloud infrastructure. TenAMP management capabilities let you designate user roles, assign provisioning rights and lock down users from deploying machines with a self-services portal that requires approval before someone is able to spin a instance up. Along with our detailed monitoring, alerting and logging capabilities- TenAMP gives you enterprise features in the public Cloud.
	</p>
	
	<h4 class="logo_start"></h4>
	<p class="content">
		
	</p>
	
	<div class="clearfix"></div>
</div>