<div class="main big_content">
	<span class="info_image info">Info</span>
	<h2 class="info_message">Pricing</h2>

	<h4 class="logo_start">Free edition</h4>
	<p class="content">
		Try Tenbrain for free with the free startup edition. There is 20 day limitation in time, and you must upgrade to the OTP method or production edition to create more than two managed servers. <a href="/account/sign_up">Sign up</a>.
	</p>

	<h4 class="logo_start">One Time Payment Method</h4>
	<p class="content">
		When you don’t have the time to go through the hassle of setting up multiple cloud accounts and want a quick & easy way to get started, Tenbrain provides you OTP methods. These methods are simple one time charges that allow you to deploy up to 10 instances across multiple providers, all without having to sign up for an actual cloud provider account.  All you need is one Tenbrain account! <a href="/account/sign_up">Sign up</a>.
	</p>
	
	<h4 class="logo_start">Give me some Cloud Action! (A.k.a) Production edition</h4>
	<p class="content">
		When you are ready to go live, upgrade to the Production edition. You'll get migrated to Tenbrain’s  super charged production edition, which is a full featured multi-cloud management platform for mission-critical work loads. <a href="/account/sign_up">Sign up</a>.
	</p>
	
	<h4 class="logo_start">Tenbrain Consulting</h4>
	<p class="content">
		Got no experience with Cloud Computing? Or want somebody to take a look at your infrastructure, and suggest improvements? Get assistance and advice from the makers of Tenbrain! Or simply get us to do it all for you. <a href="mailto:consulting@tenbrain.com">Email us</a>, or Learn more.
	</p>
	
	<div class="clearfix"></div>
</div>