<div style="display:none;">
	
	<div id="welcome-div">
		<h2>Welcome!</h2>
		<p>Welcome text to be displayed here</p>
	</div>
	
	<div id="running_instances-details">
		<h2>Your running servers</h2>
		<p>This page shows the servers you deployed and lets you control them.</p>
	</div>
	
	<div id="stopped_instances-details">
		<h2>Servers that have been stopped</h2>
		<p>This page shows stopped servers. Usually cloud providers do not charge for these. Note that some of the providers (i.e., Rackspace), do not allow stoppeng the server.</p>
	</div>
	
	<div id="terminated_instances-details">
		<h2>Servers that have been terminated</h2>
		<p>This page shows terminated servers. This is just for history of your cloud activity, you cannot do any actions on these.</p>
	</div>
	
	<div id="available_images-details">
		<h2>Images available for deployment</h2>
		<p>This page shows the images available for deployment. Right-clicking on the image and selecting "Deploy" will show you the deployment dialogue</p>
	</div>
	
	<div id="snapshots-details">
		<h2>Backups</h2>
		<p>This page shows backups you have created.</p>
	</div>
	
	<div id="load_balancers-details">
		<h2>Load Balancers</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="elastic_ips-details">
		<h2>Elastic IPs</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="account_profile-details">
		<h2>Your profile details</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_settings-details">
		<h2>Your profile settings</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_password-details">
		<h2>Password information</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_linked-details">
		<h2>Linked Accounts</h2>
		<p>This page shows the instances you deployed.</p>
	</div>
	
</div>