<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
	<?php echo $this->headLink()->appendStylesheet('/css/account.css') ?>
	<?php echo $this->headScript()->appendFile('/js/jquery-1.4.4.min.js', 'text/javascript') ?>
	<?php echo $this->headScript()->appendFile('/js/main.js', 'text/javascript') ?>
	
</head>
<body>
<?php $lt = $this->layout() ?>
<div id="container">
	<div id="header">
		<a href="/" id="logo">Home</a>
		
		<div id="account_area">
		<?php if($lt->logged_in): ?>
			<div class="signed_in_controls">
				<span class="welcome_message">Welcome, !</span><br />
				<a class="blue underlined_dash" href="/auth/logout">Sign out</a>
				<a class="blue underlined_dash" href="/control_panel">Profile</a>
			</div>
		<?php else: ?>
			<a class="blue underlined_dash" href="/auth/register">Register</a>
			<span class="login_submit" id="signin_opener">Sign in</span>
			<form action='/auth/login' method="post" accept-charset="utf-8" id="signin_controls">
				<p class="form_contents small">
					<label for="username" class="login_label">Username/Email:</label>
				</p>
				<p class="form_contents">
					<input id="username" name="sign_in_username_email" class="signin_control" type="text" size="25" />
				</p>
				<p class="form_contents small">
					<label for="password" class="login_label">Password:</label>
				</p>
				<p class="form_contents">
					<input id="password" name="sign_in_password" class="signin_control" type="password" size="25" />
				</p>
				<p class="form_contents">
					<span class="centered">
						<input type="checkbox" id="sign_in_remember" name="sign_in_remember" checked="checked" class="centered" />
						<label for="sign_in_remember" class="login_label centered">Remember me</label>
					</span>
					<input type="submit" id="sign_in" class="login_submit centered" value="Sign in" />
				</p>
				<p class="form_contents centered">
					<span class="third_party_header">Sign in with your account from:</span>
				</p>
				<div class="form_contents">
					<ul class="signin_social">
						<?php foreach($lt->third_party_auth_providers as $provider) : ?>
						<li class="control third_party small <?php echo $provider; ?>">
							<a href="auth/connect_<?php echo $provider ?>" class="social"
								title="Sign in with your <?php echo $provider ?> account" >Connect <?php echo $provider ?></a>
						</li>
						<?php endforeach; ?>
					</ul>				
				</div>
			</form>
		<?php endif; ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
	
	<?php echo $lt->content ?>
	
	<div id="helper">
		<span class="help_header"><?php echo isset($lt->short_title) ? $lt->short_title : 'Tips' ?></span>
		<span class="help_message"><?php echo isset($short_message) ? $short_message : "This is a sample text for a TenBrain help system. Mind it's size - do not put too much text here. If you want to add more help, use the one that dispays in a shaded box. That will be viewed when clicking here." ?></span>
	</div>
	
	<div class="overlay back"></div>
	<div class="overlay front">
		<span class="help_title"><?php echo isset($lt->big_title) ? $lt->big_title : 'Sample title for big help' ?></span>
		<span class="help_message"><?php echo isset($lt->big_message) ? $lt->big_message : 'Sample text for big help' ?></span>
	</div>
	
	<div id="footer_icon_hider"></div>
	<div id="footer" class="clearfix">	
		<a href="/twitter" class="control social_icon twitter" title="Follow us on Twitter!">Follow us on Twitter!</a>		
		<a href="/facebook" class="control social_icon facebook" title="We on Facebook">We are on Facebook, Too</a>
		<a href="/rss" class="control social_icon rss" title="Our Rss feed">Our Rss feed</a>
		<div id="copyright">
			<span class="copyright">All rights reserved &copy; <?php echo date('Y') ?>, TenBrain</span>
		</div>
		
		<div id="menu">
			<a class="item" href="/about">About us</a>
			<a class="item" href="/about">Item 2</a>
			<a class="item" href="/about">Item 3</a>
		</div>
	</div>
</div> <!-- end container -->

</body>
</html>