<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php $this->headLink()->appendStylesheet('/css/main.css') ?>
	<?php $this->headLink()->appendStylesheet('/css/account.css') ?>
	<?php $this->headLink()->appendStylesheet('/css/paypal.css') ?>
	<?php echo $this->headLink() ?>
	
	<?php $this->headScript()->appendFile('/js/jquery-1.4.4.min.js', 'text/javascript') ?>
	<?php $this->headScript()->appendFile('/js/main.js', 'text/javascript') ?>
	<?php $this->headScript()->appendFile('/js/pay.js', 'text/javascript') ?>
	<?php echo $this->headScript() ?>
	
</head>
<body>
<?php $lt = $this->layout() ?>
<div id="container">
	<div id="header">
		<a href="/" id="logo">Home</a>
		
		<div id="account_area">
		<?php if($lt->logged_in): ?>
			<div class="signed_in_controls">
				<span class="welcome_message">Welcome, <?php echo $lt->username ?>!</span><br />
				<a class="blue underlined_dash" href="/account/sign_out">Sign out</a>
				<a class="blue underlined_dash" href="/console">Your console</a>
			</div>
		<?php else: ?>
			<a class="blue underlined_dash" href="/account/sign_up">Register</a>
			<span class="login_submit" id="signin_opener">Sign in</span>
			<form action='/account/sign_in' method="post" accept-charset="utf-8" id="signin_controls">
				<p class="form_contents small">
					<label for="login" class="login_label">Username/Email:</label>
				</p>
				<p class="form_contents">
					<input id="login" name="login" class="signin_control" type="text" size="25" />
				</p>
				<p class="form_contents small">
					<label for="password" class="login_label">Password:</label>
				</p>
				<p class="form_contents">
					<input id="password" name="password" class="signin_control" type="password" size="25" />
				</p>
				<p class="form_contents">
					<span class="centered">
						<input type="checkbox" id="sign_in_remember" name="sign_in_remember" checked="checked" class="centered" />
						<label for="sign_in_remember" class="login_label centered">Remember me</label>
					</span>
					<input type="submit" id="sign_in" class="login_submit centered" value="Sign in" />
				</p>
				<p class="form_contents centered">
					<span class="third_party_header">Sign in with your account from:</span>
				</p>
				<div class="form_contents">
					<ul class="signin_social">
						<?php foreach($lt->third_party_auth_providers as $provider) : ?>
						<li class="control third_party small <?php echo $provider; ?>">
							<a href="/account/<?php echo $provider ?>_connect" class="social"
								title="Sign in with your <?php echo $provider ?> account" >Connect <?php echo $provider ?></a>
						</li>
						<?php endforeach; ?>
					</ul>				
				</div>
			</form>
		<?php endif; ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
	
	<?php echo $lt->content ?>
	
	<div id="helper">
		<span class="help_header"><?php echo isset($lt->short_help_title) ? $lt->short_help_title : 'Tips' ?></span>
		<span class="help_message"><?php echo isset($short_message) ? $short_message : "This is a sample text for a TenBrain help system. Mind it's size - do not put too much text here. If you want to add more help, use the one that dispays in a shaded box. That will be viewed when clicking here." ?></span>
	</div>

	<div class="overlay back"></div>
	<div class="overlay front" id="big_helper">
		<h2 class="help_title"><?php echo isset($lt->big_help_title) ? $lt->big_help_title : 'Tenbrain Features' ?></h2>
		<div class="help_message">
		<?php if(isset($lt->big_help_message)):?>
			<?php echo $lt->big_help_message ?>
		<?php else: ?>
			<h3>We take the complexity out of Cloud budgeting.</h3>
			
			<p>Tenbrain is a Open Source CccP (Cloud cost controller Platform) company. 
			We manage the cost of provisioning servers in the cloud and enterprise. 
			With Tenbrain, you get more than just a management platform. 
			You get CccP -  Our Cloud Cost Controller Platform - Get rid of the budgeting nightmare of the Cloud, and Save money while Saving your brain.</p>
			
			<b>Three main differentiators from other Cloud PaaS providers:</b>
			
			<h3>CccP - Cloud cost control Platform</h3>  
			
			
			<p>Do you know what it will cost you each moth to deploy to the Cloud? 
			One of the most frustrating and complex parts about the cloud is not how you get stuff running, it’s trying to figure out how much that will cost once you do get it running. 
			With Tenbrains CccP, you no longer need to worry about that. You simply input what your expected monthly budget and Tenbrain takes care of the rest. 
			Tenbrains CccP will automatically select the most competitive Cloud provider to deploy your infrastructure on. 
			Or it will deploy across multiple cloud providers, automatically  integrating your applications stacks- CccP does for Cloud IT budgeting what the Cloud did for the data center.</p>
			
			<h3>TenStacks- Fully integrated Open Source Components.</h3>
			
			
			<p>Deploying Open Source applications can be time consuming. 
			There are options available to deploy open source applications encapsulated in a instance. 
			But this still leaves you with a critical component missing when it comes to enterprise deployments and integration. 
			With Tenstacks, you deploy complete infrastructure stacks that are 100% integrated and 100% Open Source!</p>
			
			<h3>TenAMP- Automation, Monitoring and Provisioning</h3>
			
			
			
			<p>Automated provisioning and management of both your private and public cloud infrastructure. 
			TenAMP management capabilities let you designate user roles, assign provisioning rights and lock down users from deploying machines with a self-services portal that requires approval before someone is able to spin a instance up. 
			Along with our detailed monitoring, alerting and logging capabilities- TenAMP gives you enterprise features in the public Cloud.</p>
		<?php endif; ?>
		</div>
	</div>
	
	<div id="footer_icon_hider"></div>
	<div id="footer" class="clearfix">	
		<a href="/twitter" class="control social_icon twitter" title="Follow us on Twitter!">Follow us on Twitter!</a>		
		<a href="/facebook" class="control social_icon facebook" title="We on Facebook">We are on Facebook, Too</a>
		<a href="/rss" class="control social_icon rss" title="Our Rss feed">Our Rss feed</a>
		<div id="copyright">
			<span class="copyright">All rights reserved &copy; <?php echo date('Y') ?>, TenBrain</span>
		</div>
		
		<div id="menu">
			<a class="item" href="/about">About us</a>
			<a class="item" href="/about">Item 2</a>
			<a class="item" href="/about">Item 3</a>
		</div>
	</div>
</div> <!-- end container -->

</body>
</html>