<div style="display:none;">
	
	<div id="welcome-div">
		<h2>Welcome!</h2>
		<p>Welcome text to be displayed here</p>
	</div>
	
	<div id="running_instances-details">
		<h2>Your running instances</h2>
		<p>This page shows the instances you deployed.</p>
	</div>
	
	<div id="stopped_instances-details">
		<h2>Instances that have been stopped</h2>
		<p>This page shows the instances you deployed.</p>
	</div>
	
	<div id="terminated_instances-details">
		<h2>Instances that have previously been terminated</h2>
		<p>This page shows the instances you deployed.</p>
	</div>
	
	<div id="available_images-details">
		<h2>Images available for deployment</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="snapshots-details">
		<h2>Snapshots</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="load_balancers-details">
		<h2>Load Balancers</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="elastic_ips-details">
		<h2>Elastic IPs</h2>
		<p>This page shows the images available for deployment.</p>
	</div>
	
	<div id="account_profile-details">
		<h2>Your profile details</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_settings-details">
		<h2>Your profile settings</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_password-details">
		<h2>Password information</h2>
		<p>This page shows the instances you deployed and that are currently active.</p>
	</div>
	
	<div id="account_linked-details">
		<h2>Linked Accounts</h2>
		<p>This page shows the instances you deployed.</p>
	</div>
	
</div>