<?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/account.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/icons.css') ?>
<div class="profile_content">
	<h2>Change password</h2><br /> 
	<?php if($this->message):?>
		<p class="input_wrapper center account_success"><?php echo $this->message;?></p>
	<?php endif;?>
	<p>To safe guard your account, we <strong>strongly</strong> recommend that you pick a complex password which...</p> 
	<ol> 
		<li>is at least 8 characters long, and longer if possible</li> 
		<li>contains a mix of upper and lower case letters</li> 
		<li>includes numerals, special characters, and punctuation</li> 
		<li>is not based on any personal information</li> 
		<li>is not based on any dictionary word</li> 
	</ol>
	<div style="text-align: center;">
		<?php
		echo $this->form; 
		?>
	</div>
</div>