<?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/account.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/icons.css') ?>
<div class="profile_content">
	<h2>Profile page</h2><br />
	<p class="center">The information you provide on this page is publicly viewable.</p>
	<div style="padding:15px 0; text-align: center;">
		<span>Username: <?php echo $this->user->username;?></span>
	</div>
	<div style="padding:15px 0; text-align: center;">
		<span>Email: <?php echo $this->user->email;?></span>
	</div>
</div>